[package]
name = "terminalcollective-website"
version = "0.1.0"
edition = "2021"

[dependencies]
ratzilla = "0.0.0-alpha.4"
textwrap = "0.16.1"
rand = { version = "0.8.5", features = ["small_rng"], default-features = false }
console_error_panic_hook = "0.1.7"
